/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness by default; `?db=1` adds a `SELECT 1` readiness probe.
         *
         *     A failing probe returns a plain 503 body instead of raising, so the driver's error
         *     text (which can contain hostnames) never reaches the client and health checks don't
         *     flood Sentry.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Lineup
         * @description Generate a lineup sheet from the request body and return it as a file download.
         *
         *     `format=pdf` (default) converts through LibreOffice, which only exists in the container;
         *     `format=docx` returns the filled template directly. Nothing is stored.
         */
        post: operations["create_lineup_lineups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineups/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Saved Lineups
         * @description List saved lineups, oldest first, optionally only those made for one team
         *     (`source_team_id`). Paginated: `limit` is 1-200 (default 20), `offset` starts at 0.
         */
        get: operations["list_saved_lineups_lineups_saved_get"];
        put?: never;
        /**
         * Create Saved Lineup
         * @description Save a lineup as a frozen snapshot.
         *
         *     For the team, the opponent and each player, send either a `source_*_id` (the current name
         *     and NSSZ number are copied from the roster) or free text, never both. Cap numbers and NSSZ
         *     numbers must be unique within the lineup. Deleting the source team or player later does not
         *     change a saved lineup.
         */
        post: operations["create_saved_lineup_lineups_saved_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineups/saved/{lineup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Saved Lineup
         * @description Get one saved lineup by id, with its players ordered by cap number (404 if unknown).
         */
        get: operations["get_saved_lineup_lineups_saved__lineup_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Saved Lineup
         * @description Delete a saved lineup (404 if unknown).
         */
        delete: operations["delete_saved_lineup_lineups_saved__lineup_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineups/saved/{lineup_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate From Saved Lineup
         * @description Generate a document from a previously saved lineup.
         */
        post: operations["generate_from_saved_lineup_lineups_saved__lineup_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description List players ordered by creation time, optionally only one team's (`team_id`). Paginated:
         *     `limit` is 1-200 (default 20), `offset` starts at 0.
         */
        get: operations["list_players_players_get"];
        put?: never;
        /**
         * Create Player
         * @description Create a player, optionally on a team's roster. An unknown `team_id` returns 404.
         */
        post: operations["create_player_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Get one player by id (404 if unknown).
         */
        get: operations["get_player_players__player_id__get"];
        /**
         * Update Player
         * @description Replace a player's name, NSSZ number and team. An unknown player or `team_id` returns 404.
         */
        put: operations["update_player_players__player_id__put"];
        post?: never;
        /**
         * Delete Player
         * @description Delete a player. Always succeeds (204): saved lineups keep their own copy of the data.
         */
        delete: operations["delete_player_players__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description List teams, ordered by name. Paginated: `limit` is 1-200 (default 20) and `offset`
         *     starts at 0; the response carries `total` so clients can page.
         */
        get: operations["list_teams_teams_get"];
        put?: never;
        /**
         * Create Team
         * @description Create a team. `is_public` (default true) lists it in the opponent pool.
         */
        post: operations["create_team_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Teams Pool
         * @description Search the shared opponent pool (sign-in required). Only public teams are returned, and
         *     only their `id` and `name`. `search` is a literal, case-insensitive substring.
         */
        get: operations["search_teams_pool_teams_pool_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team
         * @description Get one team by id (404 if unknown).
         */
        get: operations["get_team_teams__team_id__get"];
        /**
         * Update Team
         * @description Rename a team (404 if unknown).
         */
        put: operations["update_team_teams__team_id__put"];
        post?: never;
        /**
         * Delete Team
         * @description Delete a team. Returns 409 while players are still on its roster; saved lineups that
         *     mention the team are unaffected because they store copies.
         */
        delete: operations["delete_team_teams__team_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FileFormat
         * @description Output format of a generated lineup, taken from the `format` query parameter.
         * @enum {string}
         */
        FileFormat: "pdf" | "docx";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Body of the health endpoint: `ok`, or `unavailable` when the database check failed.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /**
         * LineupRequest
         * @description Everything needed to fill one lineup sheet (no database involved).
         *
         *     Text fields are trimmed, must not be empty and have a maximum length. `players` holds 1 to 15
         *     entries with unique cap numbers (1-15) and unique NSSZ numbers.
         */
        LineupRequest: {
            /** Assistant Coach */
            assistant_coach: string;
            /** Ball Thrower */
            ball_thrower: string;
            /**
             * Cap
             * @enum {string}
             */
            cap: "Fehér" | "Kék";
            /** Coach */
            coach: string;
            /** Date */
            date: string;
            /** Division */
            division: string;
            /** Doctor */
            doctor: string;
            /** Match */
            match: string;
            /** Players */
            players: components["schemas"]["PlayerRequest"][];
            /** Team Leader */
            team_leader: string;
            /** Team Name */
            team_name: string;
        };
        /**
         * PaginatedPlayers
         * @description One page of players plus the total number of matching players.
         */
        PaginatedPlayers: {
            /** Items */
            items: components["schemas"]["PlayerResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PaginatedSavedLineups
         * @description One page of saved lineups plus the total number of matching lineups.
         */
        PaginatedSavedLineups: {
            /** Items */
            items: components["schemas"]["SavedLineupResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PaginatedTeams
         * @description One page of teams plus the total number of teams.
         */
        PaginatedTeams: {
            /** Items */
            items: components["schemas"]["TeamResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PlayerCreate
         * @description Body for creating a player. Text is trimmed, must not be blank or contain control
         *     characters; `team_id` (optional) must be an existing team.
         */
        PlayerCreate: {
            /** Name */
            name: string;
            /** Nssz Number */
            nssz_number: string;
            /** Team Id */
            team_id?: string | null;
        };
        /**
         * PlayerRequest
         * @description One player on the lineup sheet.
         */
        PlayerRequest: {
            /** Cap Number */
            cap_number: number;
            /** Name */
            name: string;
            /** Nssz Number */
            nssz_number: string;
        };
        /**
         * PlayerResponse
         * @description A player as returned by the API.
         */
        PlayerResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Nssz Number */
            nssz_number: string;
            /** Team Id */
            team_id: string | null;
        };
        /**
         * PlayerUpdate
         * @description Body for replacing a player's data (all fields are overwritten, including `team_id`).
         */
        PlayerUpdate: {
            /** Name */
            name: string;
            /** Nssz Number */
            nssz_number: string;
            /** Team Id */
            team_id?: string | null;
        };
        /**
         * SavedLineupCreate
         * @description Body for saving a lineup.
         *
         *     Team and opponent each need either a `source_*_id` or a name, never both. `match_name`
         *     defaults to "<team> - <opponent>". Blank optional values count as not provided. Cap numbers
         *     must be unique, and no roster player may appear twice.
         */
        SavedLineupCreate: {
            /** Assistant Coach */
            assistant_coach?: string | null;
            /** Ball Thrower */
            ball_thrower?: string | null;
            /**
             * Cap
             * @enum {string}
             */
            cap: "Fehér" | "Kék";
            /** Coach */
            coach: string;
            /** Date */
            date: string;
            /** Division */
            division: string;
            /** Doctor */
            doctor?: string | null;
            /** Match Name */
            match_name?: string | null;
            /** Opponent Name */
            opponent_name?: string | null;
            /** Players */
            players: components["schemas"]["SavedLineupPlayerCreate"][];
            /** Source Opponent Id */
            source_opponent_id?: string | null;
            /** Source Team Id */
            source_team_id?: string | null;
            /** Team Leader */
            team_leader?: string | null;
            /** Team Name */
            team_name?: string | null;
        };
        /**
         * SavedLineupPlayerCreate
         * @description One player slot: reference an existing roster player (whose current
         *     name/NSSZ number is frozen at save time) or supply free text directly, never both.
         */
        SavedLineupPlayerCreate: {
            /** Cap Number */
            cap_number: number;
            /** Name */
            name?: string | null;
            /** Nssz Number */
            nssz_number?: string | null;
            /** Source Player Id */
            source_player_id?: string | null;
        };
        /**
         * SavedLineupPlayerResponse
         * @description A player slot of a saved lineup, as frozen when it was saved.
         */
        SavedLineupPlayerResponse: {
            /** Cap Number */
            cap_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Nssz Number */
            nssz_number: string;
            /** Source Player Id */
            source_player_id: string | null;
        };
        /**
         * SavedLineupResponse
         * @description A saved lineup as returned by the API. All text is the frozen copy; `source_*_id`
         *     fields are soft references and become null if the source is deleted.
         */
        SavedLineupResponse: {
            /** Assistant Coach */
            assistant_coach: string | null;
            /** Ball Thrower */
            ball_thrower: string | null;
            /** Cap */
            cap: string;
            /** Coach */
            coach: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Date */
            date: string;
            /** Division */
            division: string;
            /** Doctor */
            doctor: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Match Name */
            match_name: string;
            /** Opponent Name */
            opponent_name: string;
            /** Players */
            players: components["schemas"]["SavedLineupPlayerResponse"][];
            /** Source Opponent Id */
            source_opponent_id: string | null;
            /** Source Team Id */
            source_team_id: string | null;
            /** Team Leader */
            team_leader: string | null;
            /** Team Name */
            team_name: string;
        };
        /**
         * TeamCreate
         * @description Body for creating a team. The name is trimmed and must not be blank or contain control
         *     characters.
         */
        TeamCreate: {
            /**
             * Is Public
             * @default true
             */
            is_public: boolean;
            /** Name */
            name: string;
        };
        /**
         * TeamDeleteResponse
         * @description Confirmation returned after a team is deleted.
         */
        TeamDeleteResponse: {
            /** Deleted */
            deleted: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * TeamPoolItem
         * @description Lightweight entry for the shared opponent pool — id + name only.
         */
        TeamPoolItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * TeamResponse
         * @description A team as returned by the API.
         */
        TeamResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
        };
        /**
         * TeamUpdate
         * @description Body for renaming a team.
         */
        TeamUpdate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: {
                /** @description Also check the database (readiness). Default: liveness only. */
                db?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_lineup_lineups_post: {
        parameters: {
            query?: {
                /** @description Output format of the generated file */
                format?: components["schemas"]["FileFormat"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_lineups_lineups_saved_get: {
        parameters: {
            query?: {
                /** @description Max items to return (1-200). */
                limit?: number;
                offset?: number;
                source_team_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSavedLineups"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_saved_lineup_lineups_saved_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedLineupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedLineupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_lineup_lineups_saved__lineup_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedLineupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_lineup_lineups_saved__lineup_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_from_saved_lineup_lineups_saved__lineup_id__generate_post: {
        parameters: {
            query?: {
                /** @description Output format: pdf or docx */
                format?: components["schemas"]["FileFormat"];
            };
            header?: never;
            path: {
                lineup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_players_get: {
        parameters: {
            query?: {
                /** @description Max items to return (1-200). */
                limit?: number;
                offset?: number;
                team_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlayers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_player_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: {
                /** @description Max items to return (1-200). */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeams"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_teams_pool_teams_pool_get: {
        parameters: {
            query?: {
                /** @description Filter by team name (literal match) */
                search?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPoolItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_teams__team_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
