blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/LasterBergamot/lineup/tree/main/docs
    about: Check the project documentation for detailed information
